ARG version
FROM almalinux:${version:-9}
ARG COURSE="AWS"
    TRAINER="SHIVA"
    DURATION="2HRS"

RUN echo "Course is ${COURSE}, trainer is ${TRAINER} and duration is ${DURATION}"
CMD ["sleep", "100"]